
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { BusinessTrip } from '@/types/business-travel';

export interface OptimalRoute {
  id: string;
  route: string[];
  estimatedCost: number;
  estimatedTime: string;
  co2Savings: number;
  recommendations: string[];
}

export interface BudgetAlert {
  id: string;
  tripId: string;
  budgetId: string;
  alertType: 'warning' | 'exceeded' | 'critical';
  currentAmount: number;
  budgetAmount: number;
  percentage: number;
  message: string;
}

export interface TimeTrackingEntry {
  id: string;
  tripId: string;
  employeeId: string;
  date: string;
  startTime: string;
  endTime: string;
  duration: number;
  type: 'travel' | 'meeting' | 'work';
  description: string;
  autoGenerated: boolean;
}

export const useIntelligentFeatures = (tripId?: string) => {
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const queryClient = useQueryClient();

  // Optimale Routen-Vorschläge
  const generateOptimalRoutes = async (destination: string, startLocation: string): Promise<OptimalRoute[]> => {
    setIsAnalyzing(true);
    try {
      // Simuliere AI-basierte Routen-Optimierung
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      const routes: OptimalRoute[] = [
        {
          id: '1',
          route: [startLocation, destination],
          estimatedCost: 250,
          estimatedTime: '2h 30min',
          co2Savings: 15,
          recommendations: ['Direktflug verfügbar', 'Günstige Tageszeit', 'Wenig CO2-Ausstoß']
        },
        {
          id: '2',
          route: [startLocation, 'Frankfurt', destination],
          estimatedCost: 180,
          estimatedTime: '4h 15min',
          co2Savings: 25,
          recommendations: ['Mit Zwischenstopp günstiger', 'Mehr Flexibilität', 'Bessere CO2-Bilanz']
        },
        {
          id: '3',
          route: [startLocation, destination],
          estimatedCost: 95,
          estimatedTime: '6h 45min',
          co2Savings: 60,
          recommendations: ['Bahnverbindung', 'Sehr umweltfreundlich', 'Arbeitszeit im Zug möglich']
        }
      ];
      
      return routes;
    } finally {
      setIsAnalyzing(false);
    }
  };

  // Budget-Verknüpfung und -Überwachung
  const linkTripToBudget = async (tripId: string, budgetId: string, projectId?: string) => {
    try {
      // Hier würde die Verknüpfung zur Datenbank erfolgen
      console.log('Verknüpfe Reise mit Budget:', { tripId, budgetId, projectId });
      
      toast.success('Reise erfolgreich mit Budget verknüpft');
      queryClient.invalidateQueries({ queryKey: ['business-trips'] });
      queryClient.invalidateQueries({ queryKey: ['budget-alerts'] });
    } catch (error) {
      toast.error('Fehler beim Verknüpfen mit Budget');
    }
  };

  // Budget-Überschreitungs-Benachrichtigungen
  const { data: budgetAlerts = [] } = useQuery({
    queryKey: ['budget-alerts', tripId],
    queryFn: async (): Promise<BudgetAlert[]> => {
      // Simuliere Budget-Überwachung
      const alerts: BudgetAlert[] = [
        {
          id: '1',
          tripId: tripId || '',
          budgetId: 'budget-1',
          alertType: 'warning',
          currentAmount: 1800,
          budgetAmount: 2000,
          percentage: 90,
          message: 'Budget zu 90% ausgeschöpft'
        }
      ];
      return alerts;
    },
    enabled: !!tripId
  });

  // Automatische Zeiterfassung für Reisezeiten
  const generateTravelTimeEntries = async (trip: BusinessTrip): Promise<TimeTrackingEntry[]> => {
    try {
      const entries: TimeTrackingEntry[] = [];
      
      // Reisezeit hin
      entries.push({
        id: `travel-${trip.id}-outbound`,
        tripId: trip.id,
        employeeId: trip.employee_id || '',
        date: trip.start_date,
        startTime: '08:00',
        endTime: '12:00',
        duration: 4,
        type: 'travel',
        description: `Anreise nach ${trip.destination}`,
        autoGenerated: true
      });

      // Arbeitszeit vor Ort (Beispiel)
      const startDate = new Date(trip.start_date);
      const endDate = new Date(trip.end_date);
      const daysDiff = Math.ceil((endDate.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24));
      
      for (let i = 0; i < daysDiff; i++) {
        const workDate = new Date(startDate);
        workDate.setDate(startDate.getDate() + i);
        
        entries.push({
          id: `work-${trip.id}-day-${i}`,
          tripId: trip.id,
          employeeId: trip.employee_id || '',
          date: workDate.toISOString().split('T')[0],
          startTime: '09:00',
          endTime: '17:00',
          duration: 8,
          type: 'work',
          description: `Arbeit in ${trip.destination} - ${trip.purpose}`,
          autoGenerated: true
        });
      }

      // Rückreise
      entries.push({
        id: `travel-${trip.id}-return`,
        tripId: trip.id,
        employeeId: trip.employee_id || '',
        date: trip.end_date,
        startTime: '14:00',
        endTime: '18:00',
        duration: 4,
        type: 'travel',
        description: `Rückreise von ${trip.destination}`,
        autoGenerated: true
      });

      return entries;
    } catch (error) {
      console.error('Fehler beim Generieren der Zeiterfassung:', error);
      return [];
    }
  };

  // Mutation für automatische Zeiterfassung
  const createTimeTrackingMutation = useMutation({
    mutationFn: generateTravelTimeEntries,
    onSuccess: (entries) => {
      toast.success(`${entries.length} Zeiterfassungseinträge automatisch erstellt`);
      queryClient.invalidateQueries({ queryKey: ['time-tracking'] });
    },
    onError: () => {
      toast.error('Fehler beim Erstellen der Zeiterfassung');
    }
  });

  // Intelligente Kostenanalyse
  const analyzeExpensePatterns = async (tripId: string) => {
    try {
      // Simuliere AI-basierte Kostenanalyse
      const analysis = {
        averageDailyCost: 180,
        categoryBreakdown: {
          'Unterkunft': 60,
          'Verpflegung': 45,
          'Transport': 75
        },
        recommendations: [
          'Frühzeitige Buchung kann 15% sparen',
          'Alternative Unterkunft in der Nähe verfügbar',
          'Bahncard könnte sich lohnen'
        ]
      };
      
      return analysis;
    } catch (error) {
      console.error('Fehler bei der Kostenanalyse:', error);
      return null;
    }
  };

  return {
    // Routen-Optimierung
    generateOptimalRoutes,
    isAnalyzing,
    
    // Budget-Features
    linkTripToBudget,
    budgetAlerts,
    
    // Zeiterfassung
    generateTravelTimeEntries,
    createTimeTrackingEntries: createTimeTrackingMutation.mutate,
    isCreatingTimeEntries: createTimeTrackingMutation.isPending,
    
    // Kostenanalyse
    analyzeExpensePatterns
  };
};
