-- =====================================================
-- Settings Definitions für business_travel Modul
-- =====================================================

-- GeneralProfilesTab (18 Definitionen)
INSERT INTO settings_definitions (module, submodule, key, name, description, value_type, default_value, category, sort_order, is_active) VALUES
('business_travel', 'general', 'travel_type_domestic', 'Inlandsreisen', 'Inlandsreisen aktivieren', 'boolean', 'true', 'general', 1, true),
('business_travel', 'general', 'travel_type_eu', 'EU-Reisen', 'EU-Reisen aktivieren', 'boolean', 'true', 'general', 2, true),
('business_travel', 'general', 'travel_type_non_eu', 'Nicht-EU-Reisen', 'Nicht-EU-Reisen aktivieren', 'boolean', 'true', 'general', 3, true),
('business_travel', 'general', 'travel_type_day_trip', 'Tagesreisen', 'Tagesreisen aktivieren', 'boolean', 'true', 'general', 4, true),
('business_travel', 'general', 'travel_type_multi_day', 'Mehrtägige Reisen', 'Mehrtägige Reisen aktivieren', 'boolean', 'true', 'general', 5, true),
('business_travel', 'general', 'required_purpose', 'Reisezweck erforderlich', 'Reisezweck muss angegeben werden', 'boolean', 'true', 'general', 6, true),
('business_travel', 'general', 'required_customer', 'Kunde erforderlich', 'Kunde muss angegeben werden', 'boolean', 'false', 'general', 7, true),
('business_travel', 'general', 'required_project', 'Projekt erforderlich', 'Projekt muss angegeben werden', 'boolean', 'false', 'general', 8, true),
('business_travel', 'general', 'required_cost_center', 'Kostenstelle erforderlich', 'Kostenstelle muss angegeben werden', 'boolean', 'true', 'general', 9, true),
('business_travel', 'general', 'dataflow_calendar', 'Kalender-Integration', 'Reisen im Kalender anzeigen', 'boolean', 'true', 'general', 10, true),
('business_travel', 'general', 'dataflow_time_tracking', 'Zeiterfassung-Integration', 'Reisezeiten in Zeiterfassung übernehmen', 'boolean', 'true', 'general', 11, true),
('business_travel', 'general', 'dataflow_absence', 'Abwesenheits-Integration', 'Reisen als Abwesenheit markieren', 'boolean', 'true', 'general', 12, true),
('business_travel', 'general', 'dataflow_payroll', 'Lohnabrechnung-Integration', 'Spesen in Lohnabrechnung übernehmen', 'boolean', 'false', 'general', 13, true),
('business_travel', 'general', 'advance_payment_enabled', 'Vorschüsse aktiviert', 'Reisekostenvorschüsse ermöglichen', 'boolean', 'true', 'general', 14, true),
('business_travel', 'general', 'advance_payment_max', 'Max. Vorschuss (€)', 'Maximaler Vorschussbetrag', 'number', '500', 'general', 15, true),
('business_travel', 'general', 'default_currency', 'Standardwährung', 'Standard-Währung für Reisekosten', 'string', '"EUR"', 'general', 16, true),
('business_travel', 'general', 'receipt_required_amount', 'Beleg ab Betrag (€)', 'Ab diesem Betrag ist ein Beleg erforderlich', 'number', '10', 'general', 17, true),
('business_travel', 'general', 'auto_save_drafts', 'Entwürfe automatisch speichern', 'Reiseanträge automatisch als Entwurf speichern', 'boolean', 'true', 'general', 18, true),

-- TravelPoliciesTab (25 Definitionen)
('business_travel', 'policies', 'enforcement_mode', 'Durchsetzungsmodus', 'Wie streng Richtlinien durchgesetzt werden', 'string', '"warning"', 'policies', 19, true),
('business_travel', 'policies', 'train_class_domestic', 'Zugklasse Inland', 'Erlaubte Zugklasse für Inlandsreisen', 'string', '"2"', 'policies', 20, true),
('business_travel', 'policies', 'train_class_international', 'Zugklasse International', 'Erlaubte Zugklasse für Auslandsreisen', 'string', '"2"', 'policies', 21, true),
('business_travel', 'policies', 'flight_class_short', 'Flugklasse Kurzstrecke', 'Erlaubte Flugklasse für Kurzstrecken', 'string', '"economy"', 'policies', 22, true),
('business_travel', 'policies', 'flight_class_medium', 'Flugklasse Mittelstrecke', 'Erlaubte Flugklasse für Mittelstrecken', 'string', '"economy"', 'policies', 23, true),
('business_travel', 'policies', 'flight_class_long', 'Flugklasse Langstrecke', 'Erlaubte Flugklasse für Langstrecken', 'string', '"business"', 'policies', 24, true),
('business_travel', 'policies', 'hotel_max_domestic', 'Max. Hotel Inland (€)', 'Maximale Hotelkosten pro Nacht Inland', 'number', '120', 'policies', 25, true),
('business_travel', 'policies', 'hotel_max_eu', 'Max. Hotel EU (€)', 'Maximale Hotelkosten pro Nacht EU', 'number', '150', 'policies', 26, true),
('business_travel', 'policies', 'hotel_max_international', 'Max. Hotel International (€)', 'Maximale Hotelkosten pro Nacht International', 'number', '200', 'policies', 27, true),
('business_travel', 'policies', 'car_rental_allowed', 'Mietwagen erlaubt', 'Mietwagen als Transportmittel erlauben', 'boolean', 'true', 'policies', 28, true),
('business_travel', 'policies', 'car_rental_class', 'Mietwagenklasse', 'Erlaubte Mietwagenklasse', 'string', '"compact"', 'policies', 29, true),
('business_travel', 'policies', 'private_car_allowed', 'Privatfahrzeug erlaubt', 'Nutzung des Privatfahrzeugs erlauben', 'boolean', 'true', 'policies', 30, true),
('business_travel', 'policies', 'private_car_rate', 'Kilometerpauschale (€)', 'Erstattung pro Kilometer Privatfahrzeug', 'number', '0.30', 'policies', 31, true),
('business_travel', 'policies', 'taxi_allowed', 'Taxi erlaubt', 'Taxi als Transportmittel erlauben', 'boolean', 'true', 'policies', 32, true),
('business_travel', 'policies', 'public_transport_preferred', 'ÖPNV bevorzugt', 'Öffentliche Verkehrsmittel bevorzugen', 'boolean', 'true', 'policies', 33, true),
('business_travel', 'policies', 'booking_advance_days', 'Buchungsvorlauf (Tage)', 'Empfohlener Buchungsvorlauf', 'number', '14', 'policies', 34, true),
('business_travel', 'policies', 'booking_advance_required', 'Vorlauf erzwingen', 'Buchungsvorlauf strikt erzwingen', 'boolean', 'false', 'policies', 35, true),
('business_travel', 'policies', 'meal_allowance_breakfast', 'Frühstückspauschale (€)', 'Pauschale für Frühstück', 'number', '12', 'policies', 36, true),
('business_travel', 'policies', 'meal_allowance_lunch', 'Mittagspauschale (€)', 'Pauschale für Mittagessen', 'number', '15', 'policies', 37, true),
('business_travel', 'policies', 'meal_allowance_dinner', 'Abendessenpauschale (€)', 'Pauschale für Abendessen', 'number', '20', 'policies', 38, true),
('business_travel', 'policies', 'wifi_reimbursement', 'WLAN-Erstattung', 'WLAN-Kosten erstatten', 'boolean', 'true', 'policies', 39, true),
('business_travel', 'policies', 'parking_reimbursement', 'Parkgebühren-Erstattung', 'Parkgebühren erstatten', 'boolean', 'true', 'policies', 40, true),
('business_travel', 'policies', 'toll_reimbursement', 'Maut-Erstattung', 'Mautgebühren erstatten', 'boolean', 'true', 'policies', 41, true),
('business_travel', 'policies', 'luggage_fee_reimbursement', 'Gepäckgebühren-Erstattung', 'Gepäckgebühren erstatten', 'boolean', 'true', 'policies', 42, true),
('business_travel', 'policies', 'cancellation_policy', 'Stornierungsrichtlinie', 'Standard-Stornierungsbedingungen', 'string', '"flexible"', 'policies', 43, true),

-- ApprovalWorkflowsTab (30 Definitionen)
('business_travel', 'approval', 'approval_required', 'Genehmigung erforderlich', 'Reisen müssen genehmigt werden', 'boolean', 'true', 'approval', 44, true),
('business_travel', 'approval', 'approval_workflow_type', 'Workflow-Typ', 'Art des Genehmigungsworkflows', 'string', '"hierarchical"', 'approval', 45, true),
('business_travel', 'approval', 'auto_approval_enabled', 'Auto-Genehmigung', 'Automatische Genehmigung aktivieren', 'boolean', 'false', 'approval', 46, true),
('business_travel', 'approval', 'auto_approval_max_amount', 'Auto-Genehmigung bis (€)', 'Maximalbetrag für Auto-Genehmigung', 'number', '200', 'approval', 47, true),
('business_travel', 'approval', 'auto_approval_max_days', 'Auto-Genehmigung bis (Tage)', 'Maximale Reisedauer für Auto-Genehmigung', 'number', '1', 'approval', 48, true),
('business_travel', 'approval', 'escalation_enabled', 'Eskalation aktiviert', 'Automatische Eskalation bei Verzögerung', 'boolean', 'true', 'approval', 49, true),
('business_travel', 'approval', 'escalation_after_hours', 'Eskalation nach (Stunden)', 'Eskalation nach X Stunden', 'number', '48', 'approval', 50, true),
('business_travel', 'approval', 'sla_first_response_hours', 'SLA Erstreaktion (Stunden)', 'Zeit bis zur ersten Reaktion', 'number', '24', 'approval', 51, true),
('business_travel', 'approval', 'sla_resolution_hours', 'SLA Lösung (Stunden)', 'Zeit bis zur finalen Entscheidung', 'number', '72', 'approval', 52, true),
('business_travel', 'approval', 'require_second_approval', 'Zweite Genehmigung', 'Zweite Genehmigung erforderlich', 'boolean', 'false', 'approval', 53, true),
('business_travel', 'approval', 'second_approval_threshold', 'Zweite Genehmigung ab (€)', 'Betrag ab dem zweite Genehmigung nötig', 'number', '1000', 'approval', 54, true),
('business_travel', 'approval', 'manager_can_delegate', 'Delegation erlaubt', 'Manager kann Genehmigung delegieren', 'boolean', 'true', 'approval', 55, true),
('business_travel', 'approval', 'substitute_approver_enabled', 'Stellvertreter aktiviert', 'Stellvertreter-Genehmiger aktivieren', 'boolean', 'true', 'approval', 56, true),
('business_travel', 'approval', 'budget_owner_approval', 'Budgetverantwortlicher', 'Genehmigung durch Budgetverantwortlichen', 'boolean', 'false', 'approval', 57, true),
('business_travel', 'approval', 'finance_approval_required', 'Finanz-Genehmigung', 'Genehmigung durch Finanzabteilung', 'boolean', 'false', 'approval', 58, true),
('business_travel', 'approval', 'finance_approval_threshold', 'Finanz-Genehmigung ab (€)', 'Betrag ab dem Finanz-Genehmigung nötig', 'number', '5000', 'approval', 59, true),
('business_travel', 'approval', 'rejection_reason_required', 'Ablehnungsgrund erforderlich', 'Bei Ablehnung muss Grund angegeben werden', 'boolean', 'true', 'approval', 60, true),
('business_travel', 'approval', 'modification_after_approval', 'Änderung nach Genehmigung', 'Änderungen nach Genehmigung erlauben', 'boolean', 'true', 'approval', 61, true),
('business_travel', 'approval', 'modification_requires_reapproval', 'Neugenehmigung bei Änderung', 'Änderungen erfordern Neugenehmigung', 'boolean', 'true', 'approval', 62, true),
('business_travel', 'approval', 'notification_on_approval', 'Benachrichtigung Genehmigung', 'Benachrichtigen bei Genehmigung', 'boolean', 'true', 'approval', 63, true),
('business_travel', 'approval', 'notification_on_rejection', 'Benachrichtigung Ablehnung', 'Benachrichtigen bei Ablehnung', 'boolean', 'true', 'approval', 64, true),
('business_travel', 'approval', 'notification_on_pending', 'Benachrichtigung Wartend', 'Benachrichtigen bei wartender Genehmigung', 'boolean', 'true', 'approval', 65, true),
('business_travel', 'approval', 'reminder_before_travel', 'Erinnerung vor Reise', 'Erinnerung vor Reiseantritt', 'boolean', 'true', 'approval', 66, true),
('business_travel', 'approval', 'reminder_days_before', 'Erinnerung Tage vorher', 'Tage vor Reise für Erinnerung', 'number', '3', 'approval', 67, true),
('business_travel', 'approval', 'parallel_approval', 'Parallele Genehmigung', 'Mehrere Genehmiger parallel', 'boolean', 'false', 'approval', 68, true),
('business_travel', 'approval', 'consensus_required', 'Konsens erforderlich', 'Alle Genehmiger müssen zustimmen', 'boolean', 'false', 'approval', 69, true),
('business_travel', 'approval', 'partial_approval', 'Teilgenehmigung', 'Teilweise Genehmigung möglich', 'boolean', 'false', 'approval', 70, true),
('business_travel', 'approval', 'retroactive_approval', 'Nachträgliche Genehmigung', 'Nachträgliche Genehmigung erlauben', 'boolean', 'true', 'approval', 71, true),
('business_travel', 'approval', 'emergency_approval', 'Notfall-Genehmigung', 'Notfall-Schnellgenehmigung aktivieren', 'boolean', 'true', 'approval', 72, true),
('business_travel', 'approval', 'emergency_max_amount', 'Notfall-Limit (€)', 'Maximalbetrag für Notfall-Genehmigung', 'number', '500', 'approval', 73, true),

-- BudgetControlTab (35 Definitionen)
('business_travel', 'budget', 'budget_tracking_enabled', 'Budget-Tracking', 'Budget-Tracking aktivieren', 'boolean', 'true', 'budget', 74, true),
('business_travel', 'budget', 'budget_period', 'Budget-Periode', 'Zeitraum für Budget', 'string', '"monthly"', 'budget', 75, true),
('business_travel', 'budget', 'primary_currency', 'Hauptwährung', 'Hauptwährung für Budgets', 'string', '"EUR"', 'budget', 76, true),
('business_travel', 'budget', 'department_budgets', 'Abteilungsbudgets', 'Budgets pro Abteilung', 'boolean', 'true', 'budget', 77, true),
('business_travel', 'budget', 'project_budgets', 'Projektbudgets', 'Budgets pro Projekt', 'boolean', 'false', 'budget', 78, true),
('business_travel', 'budget', 'employee_budgets', 'Mitarbeiterbudgets', 'Budgets pro Mitarbeiter', 'boolean', 'false', 'budget', 79, true),
('business_travel', 'budget', 'budget_warning_threshold', 'Warnschwelle (%)', 'Warnung ab X% Budgetverbrauch', 'number', '80', 'budget', 80, true),
('business_travel', 'budget', 'budget_critical_threshold', 'Kritische Schwelle (%)', 'Kritische Warnung ab X%', 'number', '95', 'budget', 81, true),
('business_travel', 'budget', 'budget_block_on_exceed', 'Blockieren bei Überschreitung', 'Buchungen bei Budgetüberschreitung blockieren', 'boolean', 'false', 'budget', 82, true),
('business_travel', 'budget', 'budget_require_approval_on_exceed', 'Genehmigung bei Überschreitung', 'Extra-Genehmigung bei Budgetüberschreitung', 'boolean', 'true', 'budget', 83, true),
('business_travel', 'budget', 'budget_carryover', 'Budget-Übertrag', 'Restbudget in nächste Periode übertragen', 'boolean', 'false', 'budget', 84, true),
('business_travel', 'budget', 'budget_carryover_max_percent', 'Max. Übertrag (%)', 'Maximaler prozentualer Übertrag', 'number', '20', 'budget', 85, true),
('business_travel', 'budget', 'forecast_enabled', 'Prognose aktiviert', 'Budget-Prognosen aktivieren', 'boolean', 'true', 'budget', 86, true),
('business_travel', 'budget', 'forecast_lookback_months', 'Prognose-Basis (Monate)', 'Monate für Prognose-Berechnung', 'number', '6', 'budget', 87, true),
('business_travel', 'budget', 'cost_allocation_enabled', 'Kostenverteilung', 'Kostenverteilung aktivieren', 'boolean', 'true', 'budget', 88, true),
('business_travel', 'budget', 'cost_allocation_method', 'Verteilungsmethode', 'Methode zur Kostenverteilung', 'string', '"cost_center"', 'budget', 89, true),
('business_travel', 'budget', 'vat_tracking', 'MwSt-Tracking', 'Mehrwertsteuer erfassen', 'boolean', 'true', 'budget', 90, true),
('business_travel', 'budget', 'vat_default_rate', 'Standard-MwSt (%)', 'Standard-Mehrwertsteuersatz', 'number', '19', 'budget', 91, true),
('business_travel', 'budget', 'expense_categories_enabled', 'Kostenkategorien', 'Kostenkategorien aktivieren', 'boolean', 'true', 'budget', 92, true),
('business_travel', 'budget', 'detailed_expense_breakdown', 'Detaillierte Aufschlüsselung', 'Detaillierte Kostenaufschlüsselung', 'boolean', 'true', 'budget', 93, true),
('business_travel', 'budget', 'real_time_expense_sync', 'Echtzeit-Sync', 'Ausgaben in Echtzeit synchronisieren', 'boolean', 'false', 'budget', 94, true),
('business_travel', 'budget', 'currency_conversion_auto', 'Auto-Währungsumrechnung', 'Automatische Währungsumrechnung', 'boolean', 'true', 'budget', 95, true),
('business_travel', 'budget', 'currency_conversion_rate_source', 'Wechselkurs-Quelle', 'Quelle für Wechselkurse', 'string', '"ecb"', 'budget', 96, true),
('business_travel', 'budget', 'budget_notifications_enabled', 'Budget-Benachrichtigungen', 'Benachrichtigungen bei Budgetänderungen', 'boolean', 'true', 'budget', 97, true),
('business_travel', 'budget', 'notify_on_50_percent', 'Benachrichtigung 50%', 'Benachrichtigung bei 50% Verbrauch', 'boolean', 'false', 'budget', 98, true),
('business_travel', 'budget', 'notify_on_80_percent', 'Benachrichtigung 80%', 'Benachrichtigung bei 80% Verbrauch', 'boolean', 'true', 'budget', 99, true),
('business_travel', 'budget', 'notify_on_100_percent', 'Benachrichtigung 100%', 'Benachrichtigung bei 100% Verbrauch', 'boolean', 'true', 'budget', 100, true),
('business_travel', 'budget', 'monthly_budget_review', 'Monatliche Prüfung', 'Monatliche Budget-Prüfung', 'boolean', 'true', 'budget', 101, true),
('business_travel', 'budget', 'quarterly_budget_review', 'Quartals-Prüfung', 'Quartalsweise Budget-Prüfung', 'boolean', 'true', 'budget', 102, true),
('business_travel', 'budget', 'annual_budget_planning', 'Jahresplanung', 'Jährliche Budget-Planung', 'boolean', 'true', 'budget', 103, true),
('business_travel', 'budget', 'savings_tracking', 'Einsparungs-Tracking', 'Einsparungen verfolgen', 'boolean', 'true', 'budget', 104, true),
('business_travel', 'budget', 'negotiated_rates_enabled', 'Verhandelte Raten', 'Verhandelte Unternehmensraten nutzen', 'boolean', 'true', 'budget', 105, true),
('business_travel', 'budget', 'preferred_vendor_bonus', 'Bevorzugter Anbieter Bonus', 'Bonus für bevorzugte Anbieter', 'boolean', 'false', 'budget', 106, true),
('business_travel', 'budget', 'budget_dashboard_enabled', 'Budget-Dashboard', 'Budget-Dashboard anzeigen', 'boolean', 'true', 'budget', 107, true),
('business_travel', 'budget', 'budget_export_enabled', 'Budget-Export', 'Budget-Daten exportieren', 'boolean', 'true', 'budget', 108, true),

-- PerDiemsRulesTab (40 Definitionen)
('business_travel', 'per_diem', 'per_diem_enabled', 'Tagespauschalen aktiv', 'Tagespauschalen aktivieren', 'boolean', 'true', 'per_diem', 109, true),
('business_travel', 'per_diem', 'per_diem_calculation_method', 'Berechnungsmethode', 'Methode zur Tagespauschalen-Berechnung', 'string', '"german_law"', 'per_diem', 110, true),
('business_travel', 'per_diem', 'per_diem_domestic_full', 'Volle Pauschale Inland (€)', 'Volle Tagespauschale Inland', 'number', '28', 'per_diem', 111, true),
('business_travel', 'per_diem', 'per_diem_domestic_partial', 'Teilpauschale Inland (€)', 'Teilpauschale Inland (An-/Abreisetag)', 'number', '14', 'per_diem', 112, true),
('business_travel', 'per_diem', 'per_diem_min_hours_full', 'Min. Stunden volle Pauschale', 'Mindestdauer für volle Pauschale', 'number', '24', 'per_diem', 113, true),
('business_travel', 'per_diem', 'per_diem_min_hours_partial', 'Min. Stunden Teilpauschale', 'Mindestdauer für Teilpauschale', 'number', '8', 'per_diem', 114, true),
('business_travel', 'per_diem', 'meal_reduction_breakfast', 'Kürzung Frühstück (%)', 'Kürzung bei gestelltem Frühstück', 'number', '20', 'per_diem', 115, true),
('business_travel', 'per_diem', 'meal_reduction_lunch', 'Kürzung Mittagessen (%)', 'Kürzung bei gestelltem Mittagessen', 'number', '40', 'per_diem', 116, true),
('business_travel', 'per_diem', 'meal_reduction_dinner', 'Kürzung Abendessen (%)', 'Kürzung bei gestelltem Abendessen', 'number', '40', 'per_diem', 117, true),
('business_travel', 'per_diem', 'hotel_breakfast_auto_reduction', 'Auto-Kürzung Hotelfrühstück', 'Automatische Kürzung bei Hotelfrühstück', 'boolean', 'true', 'per_diem', 118, true),
('business_travel', 'per_diem', 'international_per_diem_tables', 'Internationale Pauschalen', 'Länderspezifische Pauschalen nutzen', 'boolean', 'true', 'per_diem', 119, true),
('business_travel', 'per_diem', 'per_diem_auto_calculate', 'Auto-Berechnung', 'Automatische Pauschalen-Berechnung', 'boolean', 'true', 'per_diem', 120, true),
('business_travel', 'per_diem', 'per_diem_manual_override', 'Manuelle Überschreibung', 'Manuelle Änderung der Pauschalen erlauben', 'boolean', 'false', 'per_diem', 121, true),
('business_travel', 'per_diem', 'mileage_enabled', 'Kilometergeld aktiv', 'Kilometerpauschale aktivieren', 'boolean', 'true', 'per_diem', 122, true),
('business_travel', 'per_diem', 'mileage_rate_car', 'Km-Pauschale Auto (€)', 'Kilometerpauschale für PKW', 'number', '0.30', 'per_diem', 123, true),
('business_travel', 'per_diem', 'mileage_rate_motorcycle', 'Km-Pauschale Motorrad (€)', 'Kilometerpauschale für Motorrad', 'number', '0.20', 'per_diem', 124, true),
('business_travel', 'per_diem', 'mileage_rate_bicycle', 'Km-Pauschale Fahrrad (€)', 'Kilometerpauschale für Fahrrad', 'number', '0.05', 'per_diem', 125, true),
('business_travel', 'per_diem', 'mileage_max_km_per_trip', 'Max. km pro Fahrt', '0 = unbegrenzt', 'number', '0', 'per_diem', 126, true),
('business_travel', 'per_diem', 'mileage_max_km_per_month', 'Max. km pro Monat', '0 = unbegrenzt', 'number', '0', 'per_diem', 127, true),
('business_travel', 'per_diem', 'mileage_route_verification', 'Routenverifizierung', 'Gefahrene Route verifizieren', 'boolean', 'false', 'per_diem', 128, true),
('business_travel', 'per_diem', 'receipt_required_all', 'Beleg immer erforderlich', 'Beleg für alle Ausgaben erforderlich', 'boolean', 'false', 'per_diem', 129, true),
('business_travel', 'per_diem', 'receipt_required_above', 'Beleg erforderlich ab (€)', 'Beleg erforderlich ab diesem Betrag', 'number', '10', 'per_diem', 130, true),
('business_travel', 'per_diem', 'receipt_digital_allowed', 'Digitale Belege erlaubt', 'Digitale Belege akzeptieren', 'boolean', 'true', 'per_diem', 131, true),
('business_travel', 'per_diem', 'receipt_photo_quality', 'Foto-Qualität', 'Erforderliche Qualität für Belegfotos', 'string', '"medium"', 'per_diem', 132, true),
('business_travel', 'per_diem', 'receipt_ocr_enabled', 'OCR aktiviert', 'Automatische Belegerkennung', 'boolean', 'true', 'per_diem', 133, true),
('business_travel', 'per_diem', 'receipt_validation_enabled', 'Beleg-Validierung', 'Automatische Belegvalidierung', 'boolean', 'true', 'per_diem', 134, true),
('business_travel', 'per_diem', 'duplicate_receipt_check', 'Duplikatprüfung', 'Doppelte Belege erkennen', 'boolean', 'true', 'per_diem', 135, true),
('business_travel', 'per_diem', 'receipt_retention_years', 'Aufbewahrung (Jahre)', 'Aufbewahrungsdauer für Belege', 'number', '10', 'per_diem', 136, true),
('business_travel', 'per_diem', 'entertainment_expenses_enabled', 'Bewirtungskosten', 'Bewirtungskosten aktivieren', 'boolean', 'true', 'per_diem', 137, true),
('business_travel', 'per_diem', 'entertainment_max_per_person', 'Max. Bewirtung/Person (€)', 'Maximale Bewirtungskosten pro Person', 'number', '50', 'per_diem', 138, true),
('business_travel', 'per_diem', 'entertainment_require_attendees', 'Teilnehmer erforderlich', 'Teilnehmerliste bei Bewirtung erforderlich', 'boolean', 'true', 'per_diem', 139, true),
('business_travel', 'per_diem', 'entertainment_business_purpose', 'Geschäftszweck erforderlich', 'Geschäftlicher Anlass erforderlich', 'boolean', 'true', 'per_diem', 140, true),
('business_travel', 'per_diem', 'tips_allowed', 'Trinkgeld erlaubt', 'Trinkgeld als Ausgabe erlauben', 'boolean', 'true', 'per_diem', 141, true),
('business_travel', 'per_diem', 'tips_max_percent', 'Max. Trinkgeld (%)', 'Maximales Trinkgeld in Prozent', 'number', '15', 'per_diem', 142, true),
('business_travel', 'per_diem', 'gifts_allowed', 'Geschenke erlaubt', 'Kundengeschenke als Ausgabe erlauben', 'boolean', 'true', 'per_diem', 143, true),
('business_travel', 'per_diem', 'gifts_max_amount', 'Max. Geschenk (€)', 'Maximaler Geschenkwert', 'number', '35', 'per_diem', 144, true),
('business_travel', 'per_diem', 'incidentals_enabled', 'Nebenkosten', 'Nebenkosten aktivieren', 'boolean', 'true', 'per_diem', 145, true),
('business_travel', 'per_diem', 'incidentals_daily_limit', 'Nebenkosten Tageslimit (€)', 'Tägliches Limit für Nebenkosten', 'number', '20', 'per_diem', 146, true),
('business_travel', 'per_diem', 'laundry_reimbursement', 'Wäscheservice', 'Wäschekosten bei langen Reisen erstatten', 'boolean', 'true', 'per_diem', 147, true),
('business_travel', 'per_diem', 'laundry_min_trip_days', 'Wäsche ab Tagen', 'Mindest-Reisedauer für Wäscheerstattung', 'number', '5', 'per_diem', 148, true)
ON CONFLICT (module, key) DO NOTHING;