-- Füge fehlende Berechtigungen für superadmin hinzu
INSERT INTO public.role_permission_matrix (role, module_name, is_visible, allowed_actions, visible_fields, editable_fields, allowed_notifications) VALUES
('superadmin', 'Dashboard', true, 
 ARRAY['view'], 
 '{"all": true}', '{"all": true}', ARRAY['push']),
('superadmin', 'Abwesenheit', true,
 ARRAY['view', 'create', 'edit', 'approve', 'export'], 
 '{"all": true}', '{"all": true}', ARRAY['push', 'email']),
('superadmin', 'Aufgaben', true,
 ARRAY['view', 'create', 'edit', 'delete', 'export'], 
 '{"all": true}', '{"all": true}', ARRAY['push']),
('superadmin', 'Projekte', true,
 ARRAY['view', 'create', 'edit', 'delete', 'export'], 
 '{"all": true}', '{"all": true}', ARRAY['push', 'email']),
('superadmin', 'Lohn & Gehalt', true,
 ARRAY['view', 'create', 'edit', 'export'], 
 '{"all": true}', '{"all": true}', ARRAY['email']),
('superadmin', 'Recruiting', true,
 ARRAY['view', 'create', 'edit', 'delete', 'export'], 
 '{"all": true}', '{"all": true}', ARRAY['push', 'email']),
('superadmin', 'Performance', true,
 ARRAY['view', 'create', 'edit', 'approve', 'export'], 
 '{"all": true}', '{"all": true}', ARRAY['push', 'email'])
ON CONFLICT (role, module_name) DO NOTHING;

-- Füge Berechtigungen für admin hinzu
INSERT INTO public.role_permission_matrix (role, module_name, is_visible, allowed_actions, visible_fields, editable_fields, allowed_notifications) VALUES
('admin', 'Dashboard', true, 
 ARRAY['view'], 
 '{"basic": true}', '{"basic": true}', ARRAY['push']),
('admin', 'Mitarbeiter', true, 
 ARRAY['view', 'create', 'edit'], 
 '{"all": true}', '{"basic": true}', ARRAY['push', 'email']),
('admin', 'Zeiterfassung', true,
 ARRAY['view', 'edit', 'approve'], 
 '{"all": true}', '{"limited": true}', ARRAY['push', 'email']),
('admin', 'Abwesenheit', true,
 ARRAY['view', 'approve', 'export'], 
 '{"all": true}', '{"limited": true}', ARRAY['push', 'email']),
('admin', 'Projekte', true,
 ARRAY['view', 'create', 'edit', 'export'], 
 '{"all": true}', '{"all": true}', ARRAY['push', 'email']),
('admin', 'Dokumente', true,
 ARRAY['view', 'upload', 'export'], 
 '{"all": true}', '{"limited": true}', ARRAY['email']),
('admin', 'Aufgaben', true,
 ARRAY['view', 'create', 'edit'], 
 '{"all": true}', '{"all": true}', ARRAY['push']),
('admin', 'Performance', true,
 ARRAY['view', 'create', 'edit'], 
 '{"all": true}', '{"all": true}', ARRAY['push', 'email']),
('admin', 'Recruiting', true,
 ARRAY['view', 'create', 'edit'], 
 '{"all": true}', '{"all": true}', ARRAY['push', 'email']),
('admin', 'Einstellungen', true,
 ARRAY['view', 'edit'], 
 '{"limited": true}', '{"limited": true}', ARRAY[]::TEXT[])
ON CONFLICT (role, module_name) DO NOTHING;

-- Füge Berechtigungen für employee hinzu
INSERT INTO public.role_permission_matrix (role, module_name, is_visible, allowed_actions, visible_fields, editable_fields, allowed_notifications) VALUES
('employee', 'Dashboard', true, 
 ARRAY['view'], 
 '{"basic": true}', '{}', ARRAY['push']),
('employee', 'Zeiterfassung', true,
 ARRAY['view', 'create', 'edit'], 
 '{"own": true}', '{"own": true}', ARRAY['push']),
('employee', 'Abwesenheit', true,
 ARRAY['view', 'create'], 
 '{"own": true}', '{"own": true}', ARRAY['push', 'email']),
('employee', 'Aufgaben', true,
 ARRAY['view', 'create', 'edit'], 
 '{"assigned": true}', '{"assigned": true}', ARRAY['push']),
('employee', 'Projekte', true,
 ARRAY['view'], 
 '{"assigned": true}', '{}', ARRAY['push']),
('employee', 'Dokumente', true,
 ARRAY['view'], 
 '{"public": true}', '{}', ARRAY[]::TEXT[]),
('employee', 'Performance', true,
 ARRAY['view'], 
 '{"own": true}', '{"limited": true}', ARRAY['push'])
ON CONFLICT (role, module_name) DO NOTHING;