-- VisaPassportsTab, Providers, Sustainability, Security, Notifications, Roles, Reporting

INSERT INTO settings_definitions (module, submodule, key, name, description, value_type, default_value, category, sort_order, is_active) VALUES
('business_travel', 'visa', 'visa_tracking_enabled', 'Visum-Tracking', 'Visum-Verwaltung aktivieren', 'boolean', 'true', 'visa', 149, true),
('business_travel', 'visa', 'passport_tracking_enabled', 'Reisepass-Tracking', 'Reisepass-Verwaltung aktivieren', 'boolean', 'true', 'visa', 150, true),
('business_travel', 'visa', 'reminder_passport_expiry', 'Pass-Ablauf Erinnerung', 'Erinnerung vor Pass-Ablauf', 'boolean', 'true', 'visa', 151, true),
('business_travel', 'visa', 'reminder_passport_months', 'Pass-Erinnerung Monate', 'Monate vor Ablauf erinnern', 'number', '6', 'visa', 152, true),
('business_travel', 'visa', 'reminder_visa_expiry', 'Visum-Ablauf Erinnerung', 'Erinnerung vor Visum-Ablauf', 'boolean', 'true', 'visa', 153, true),
('business_travel', 'visa', 'reminder_visa_months', 'Visum-Erinnerung Monate', 'Monate vor Ablauf erinnern', 'number', '3', 'visa', 154, true),
('business_travel', 'visa', 'require_valid_passport', 'Gültiger Pass erforderlich', 'Gültigen Pass für Buchung prüfen', 'boolean', 'true', 'visa', 155, true),
('business_travel', 'visa', 'require_valid_visa', 'Gültiges Visum erforderlich', 'Gültiges Visum für Buchung prüfen', 'boolean', 'true', 'visa', 156, true),
('business_travel', 'visa', 'travel_insurance_required', 'Reiseversicherung erforderlich', 'Reiseversicherung muss vorhanden sein', 'boolean', 'true', 'visa', 157, true),
('business_travel', 'visa', 'travel_advisory_check', 'Reisehinweise prüfen', 'Aktuelle Reisehinweise anzeigen', 'boolean', 'true', 'visa', 158, true),
('business_travel', 'integrations', 'booking_provider_enabled', 'Buchungsanbieter', 'Externe Buchungsanbieter aktivieren', 'boolean', 'false', 'integrations', 184, true),
('business_travel', 'integrations', 'calendar_sync_enabled', 'Kalender-Sync', 'Kalender synchronisieren', 'boolean', 'true', 'integrations', 191, true),
('business_travel', 'integrations', 'erp_integration', 'ERP-Integration', 'ERP-System integrieren', 'boolean', 'false', 'integrations', 189, true),
('business_travel', 'integrations', 'hr_system_integration', 'HR-Integration', 'HR-System integrieren', 'boolean', 'false', 'integrations', 190, true),
('business_travel', 'sustainability', 'sustainability_tracking', 'Nachhaltigkeits-Tracking', 'CO2-Tracking aktivieren', 'boolean', 'true', 'sustainability', 194, true),
('business_travel', 'sustainability', 'co2_display_enabled', 'CO2-Anzeige', 'CO2-Werte anzeigen', 'boolean', 'true', 'sustainability', 195, true),
('business_travel', 'sustainability', 'co2_offset_offered', 'CO2-Kompensation anbieten', 'CO2-Kompensation anbieten', 'boolean', 'true', 'sustainability', 196, true),
('business_travel', 'sustainability', 'green_travel_incentive', 'Grüne Reise Anreize', 'Anreize für umweltfreundliche Reisen', 'boolean', 'true', 'sustainability', 198, true),
('business_travel', 'sustainability', 'train_vs_flight_suggestion', 'Bahn statt Flug', 'Bahn als Alternative vorschlagen', 'boolean', 'true', 'sustainability', 199, true),
('business_travel', 'security', 'location_tracking_enabled', 'Standort-Tracking', 'Standort-Tracking während Reise', 'boolean', 'false', 'security', 204, true),
('business_travel', 'security', 'check_in_required', 'Check-In erforderlich', 'Regelmäßige Check-Ins erforderlich', 'boolean', 'true', 'security', 205, true),
('business_travel', 'security', 'sos_button_enabled', 'SOS-Button', 'Notfall-Button aktivieren', 'boolean', 'true', 'security', 207, true),
('business_travel', 'notifications', 'email_notifications', 'E-Mail Benachrichtigungen', 'E-Mail Benachrichtigungen aktivieren', 'boolean', 'true', 'notifications', 209, true),
('business_travel', 'notifications', 'push_notifications', 'Push Benachrichtigungen', 'Push Benachrichtigungen aktivieren', 'boolean', 'true', 'notifications', 210, true),
('business_travel', 'notifications', 'sms_notifications', 'SMS Benachrichtigungen', 'SMS Benachrichtigungen aktivieren', 'boolean', 'false', 'notifications', 211, true),
('business_travel', 'roles', 'role_employee_enabled', 'Mitarbeiter-Rolle', 'Mitarbeiter können Reisen beantragen', 'boolean', 'true', 'roles', 214, true),
('business_travel', 'roles', 'role_manager_enabled', 'Manager-Rolle', 'Manager können genehmigen', 'boolean', 'true', 'roles', 215, true),
('business_travel', 'roles', 'visibility_own_trips', 'Eigene Reisen', 'Eigene Reisen sichtbar', 'boolean', 'true', 'roles', 219, true),
('business_travel', 'roles', 'visibility_team_trips', 'Team-Reisen', 'Team-Reisen für Manager sichtbar', 'boolean', 'true', 'roles', 220, true),
('business_travel', 'roles', 'can_view_reports', 'Berichte einsehen', 'Berichte einsehen möglich', 'boolean', 'true', 'roles', 225, true),
('business_travel', 'reporting', 'reporting_enabled', 'Reporting aktiviert', 'Reporting-Funktionen aktivieren', 'boolean', 'true', 'reporting', 229, true),
('business_travel', 'reporting', 'standard_reports_enabled', 'Standard-Berichte', 'Standard-Berichte aktivieren', 'boolean', 'true', 'reporting', 230, true),
('business_travel', 'reporting', 'audit_trail_enabled', 'Audit-Trail', 'Änderungsverfolgung aktivieren', 'boolean', 'true', 'reporting', 233, true),
('business_travel', 'reporting', 'analytics_dashboard', 'Analytics-Dashboard', 'Analytics-Dashboard anzeigen', 'boolean', 'true', 'reporting', 236, true),
('business_travel', 'reporting', 'kpi_tracking_enabled', 'KPI-Tracking', 'KPI-Tracking aktivieren', 'boolean', 'true', 'reporting', 237, true)
ON CONFLICT (module, key) DO NOTHING;