-- Teil 1: role_permission_matrix komplett bereinigen und neu aufbauen

-- Alte inkonsistente Einträge für die 4 Haupt-Rollen entfernen
DELETE FROM role_permission_matrix 
WHERE role IN ('employee', 'team_lead', 'hr_admin', 'admin', 'hr_manager', 'manager');

-- MITARBEITER (employee) - Nur Self-Service Module (80/20 Regel)
INSERT INTO role_permission_matrix (role, module_name, is_visible, allowed_actions) VALUES
-- Basis-Module (sichtbar)
('employee', 'dashboard', true, ARRAY['view']),
('employee', 'today', true, ARRAY['view']),
('employee', 'notifications', true, ARRAY['view', 'edit', 'delete']),
('employee', 'profil', true, ARRAY['view', 'edit']),
('employee', 'absence', true, ARRAY['view', 'create', 'edit']),
('employee', 'time_tracking', true, ARRAY['view', 'create', 'edit']),
('employee', 'calendar', true, ARRAY['view']),
('employee', 'chat', true, ARRAY['view', 'create', 'edit']),
('employee', 'tasks', true, ARRAY['view', 'create', 'edit']),
('employee', 'documents', true, ARRAY['view', 'create']),
('employee', 'helpdesk', true, ARRAY['view', 'create']),
('employee', 'goals', true, ARRAY['view', 'create', 'edit']),
('employee', 'knowledge_hub', true, ARRAY['view']),
('employee', 'sick_leave', true, ARRAY['view', 'create']),
('employee', 'voicemail', true, ARRAY['view']),
-- VERSTECKTE Module für Mitarbeiter
('employee', 'projects', false, ARRAY[]::text[]),
('employee', 'performance', false, ARRAY[]::text[]),
('employee', 'shift_planning', false, ARRAY[]::text[]),
('employee', 'employees', false, ARRAY[]::text[]),
('employee', 'pulse_surveys', false, ARRAY[]::text[]),
('employee', 'payroll', false, ARRAY[]::text[]),
('employee', 'recruiting', false, ARRAY[]::text[]),
('employee', 'onboarding', false, ARRAY[]::text[]),
('employee', 'reports', false, ARRAY[]::text[]),
('employee', 'compliance', false, ARRAY[]::text[]),
('employee', 'workforce_planning', false, ARRAY[]::text[]),
('employee', 'hr_organization_design', false, ARRAY[]::text[]),
('employee', 'budget', false, ARRAY[]::text[]),
('employee', 'workflow', false, ARRAY[]::text[]),
('employee', 'ai', false, ARRAY[]::text[]),
('employee', 'global_mobility', false, ARRAY[]::text[]),
('employee', 'business_travel', false, ARRAY[]::text[]),
('employee', 'expenses', false, ARRAY[]::text[]),
('employee', 'innovation', false, ARRAY[]::text[]),
('employee', 'environment', false, ARRAY[]::text[]),
('employee', 'rewards', false, ARRAY[]::text[]),
('employee', 'settings', false, ARRAY[]::text[]);

-- TEAMLEITER (team_lead) - Team-Verantwortung
INSERT INTO role_permission_matrix (role, module_name, is_visible, allowed_actions) VALUES
('team_lead', 'dashboard', true, ARRAY['view']),
('team_lead', 'today', true, ARRAY['view']),
('team_lead', 'notifications', true, ARRAY['view', 'edit', 'delete']),
('team_lead', 'profil', true, ARRAY['view', 'edit']),
('team_lead', 'absence', true, ARRAY['view', 'create', 'edit', 'approve']),
('team_lead', 'time_tracking', true, ARRAY['view', 'create', 'edit']),
('team_lead', 'calendar', true, ARRAY['view', 'edit']),
('team_lead', 'chat', true, ARRAY['view', 'create', 'edit']),
('team_lead', 'tasks', true, ARRAY['view', 'create', 'edit', 'assign']),
('team_lead', 'documents', true, ARRAY['view', 'create', 'edit']),
('team_lead', 'helpdesk', true, ARRAY['view', 'create']),
('team_lead', 'goals', true, ARRAY['view', 'create', 'edit']),
('team_lead', 'knowledge_hub', true, ARRAY['view', 'create']),
('team_lead', 'sick_leave', true, ARRAY['view', 'create']),
('team_lead', 'voicemail', true, ARRAY['view']),
('team_lead', 'projects', true, ARRAY['view', 'edit']),
('team_lead', 'performance', true, ARRAY['view']),
('team_lead', 'shift_planning', true, ARRAY['view', 'edit']),
('team_lead', 'employees', true, ARRAY['view']),
-- VERSTECKTE Module für Teamleiter
('team_lead', 'pulse_surveys', false, ARRAY[]::text[]),
('team_lead', 'payroll', false, ARRAY[]::text[]),
('team_lead', 'recruiting', false, ARRAY[]::text[]),
('team_lead', 'onboarding', false, ARRAY[]::text[]),
('team_lead', 'reports', false, ARRAY[]::text[]),
('team_lead', 'compliance', false, ARRAY[]::text[]),
('team_lead', 'workforce_planning', false, ARRAY[]::text[]),
('team_lead', 'hr_organization_design', false, ARRAY[]::text[]),
('team_lead', 'budget', false, ARRAY[]::text[]),
('team_lead', 'workflow', false, ARRAY[]::text[]),
('team_lead', 'ai', false, ARRAY[]::text[]),
('team_lead', 'global_mobility', false, ARRAY[]::text[]),
('team_lead', 'business_travel', false, ARRAY[]::text[]),
('team_lead', 'expenses', false, ARRAY[]::text[]),
('team_lead', 'innovation', false, ARRAY[]::text[]),
('team_lead', 'environment', false, ARRAY[]::text[]),
('team_lead', 'rewards', false, ARRAY[]::text[]),
('team_lead', 'settings', false, ARRAY[]::text[]);

-- HR ADMIN (hr_admin) - HR-Vollzugriff
INSERT INTO role_permission_matrix (role, module_name, is_visible, allowed_actions) VALUES
('hr_admin', 'dashboard', true, ARRAY['view', 'export']),
('hr_admin', 'today', true, ARRAY['view']),
('hr_admin', 'notifications', true, ARRAY['view', 'edit', 'delete']),
('hr_admin', 'profil', true, ARRAY['view', 'edit']),
('hr_admin', 'absence', true, ARRAY['view', 'create', 'edit', 'delete', 'approve', 'export']),
('hr_admin', 'time_tracking', true, ARRAY['view', 'create', 'edit', 'export']),
('hr_admin', 'calendar', true, ARRAY['view', 'edit']),
('hr_admin', 'chat', true, ARRAY['view', 'create', 'edit']),
('hr_admin', 'tasks', true, ARRAY['view', 'create', 'edit', 'assign']),
('hr_admin', 'documents', true, ARRAY['view', 'create', 'edit', 'delete']),
('hr_admin', 'helpdesk', true, ARRAY['view', 'create', 'edit', 'assign']),
('hr_admin', 'goals', true, ARRAY['view', 'create', 'edit']),
('hr_admin', 'knowledge_hub', true, ARRAY['view', 'create', 'edit']),
('hr_admin', 'sick_leave', true, ARRAY['view', 'create', 'edit']),
('hr_admin', 'voicemail', true, ARRAY['view', 'edit']),
('hr_admin', 'projects', true, ARRAY['view', 'edit']),
('hr_admin', 'performance', true, ARRAY['view', 'edit', 'approve']),
('hr_admin', 'shift_planning', true, ARRAY['view', 'create', 'edit']),
('hr_admin', 'employees', true, ARRAY['view', 'create', 'edit', 'delete', 'export']),
('hr_admin', 'pulse_surveys', true, ARRAY['view', 'create', 'edit']),
('hr_admin', 'payroll', true, ARRAY['view', 'export']),
('hr_admin', 'recruiting', true, ARRAY['view', 'create', 'edit', 'approve']),
('hr_admin', 'onboarding', true, ARRAY['view', 'create', 'edit']),
('hr_admin', 'reports', true, ARRAY['view', 'export']),
('hr_admin', 'compliance', true, ARRAY['view', 'edit']),
('hr_admin', 'global_mobility', true, ARRAY['view', 'edit']),
('hr_admin', 'business_travel', true, ARRAY['view', 'edit']),
('hr_admin', 'expenses', true, ARRAY['view', 'edit']),
('hr_admin', 'environment', true, ARRAY['view', 'edit']),
('hr_admin', 'rewards', true, ARRAY['view', 'edit']),
('hr_admin', 'settings', true, ARRAY['view', 'edit']),
-- VERSTECKTE Module für HR Admin
('hr_admin', 'workforce_planning', false, ARRAY[]::text[]),
('hr_admin', 'hr_organization_design', false, ARRAY[]::text[]),
('hr_admin', 'budget', false, ARRAY[]::text[]),
('hr_admin', 'workflow', false, ARRAY[]::text[]),
('hr_admin', 'ai', false, ARRAY[]::text[]),
('hr_admin', 'innovation', false, ARRAY[]::text[]);

-- ADMIN - Vollzugriff auf alles
INSERT INTO role_permission_matrix (role, module_name, is_visible, allowed_actions) VALUES
('admin', 'dashboard', true, ARRAY['view', 'create', 'edit', 'delete', 'export']),
('admin', 'today', true, ARRAY['view', 'edit']),
('admin', 'notifications', true, ARRAY['view', 'create', 'edit', 'delete']),
('admin', 'profil', true, ARRAY['view', 'create', 'edit', 'delete']),
('admin', 'absence', true, ARRAY['view', 'create', 'edit', 'delete', 'approve', 'export']),
('admin', 'time_tracking', true, ARRAY['view', 'create', 'edit', 'delete', 'export']),
('admin', 'calendar', true, ARRAY['view', 'create', 'edit', 'delete']),
('admin', 'chat', true, ARRAY['view', 'create', 'edit', 'delete']),
('admin', 'tasks', true, ARRAY['view', 'create', 'edit', 'delete', 'assign']),
('admin', 'documents', true, ARRAY['view', 'create', 'edit', 'delete', 'export']),
('admin', 'helpdesk', true, ARRAY['view', 'create', 'edit', 'delete', 'assign']),
('admin', 'goals', true, ARRAY['view', 'create', 'edit', 'delete']),
('admin', 'knowledge_hub', true, ARRAY['view', 'create', 'edit', 'delete']),
('admin', 'sick_leave', true, ARRAY['view', 'create', 'edit', 'delete']),
('admin', 'voicemail', true, ARRAY['view', 'create', 'edit', 'delete']),
('admin', 'projects', true, ARRAY['view', 'create', 'edit', 'delete']),
('admin', 'performance', true, ARRAY['view', 'create', 'edit', 'delete', 'approve']),
('admin', 'shift_planning', true, ARRAY['view', 'create', 'edit', 'delete']),
('admin', 'employees', true, ARRAY['view', 'create', 'edit', 'delete', 'export', 'impersonate']),
('admin', 'pulse_surveys', true, ARRAY['view', 'create', 'edit', 'delete']),
('admin', 'payroll', true, ARRAY['view', 'create', 'edit', 'delete', 'export']),
('admin', 'recruiting', true, ARRAY['view', 'create', 'edit', 'delete', 'approve', 'export']),
('admin', 'onboarding', true, ARRAY['view', 'create', 'edit', 'delete']),
('admin', 'reports', true, ARRAY['view', 'create', 'edit', 'delete', 'export']),
('admin', 'compliance', true, ARRAY['view', 'create', 'edit', 'delete', 'export']),
('admin', 'global_mobility', true, ARRAY['view', 'create', 'edit', 'delete']),
('admin', 'business_travel', true, ARRAY['view', 'create', 'edit', 'delete']),
('admin', 'expenses', true, ARRAY['view', 'create', 'edit', 'delete']),
('admin', 'environment', true, ARRAY['view', 'create', 'edit', 'delete']),
('admin', 'rewards', true, ARRAY['view', 'create', 'edit', 'delete']),
('admin', 'settings', true, ARRAY['view', 'create', 'edit', 'delete']),
('admin', 'workforce_planning', true, ARRAY['view', 'create', 'edit', 'delete']),
('admin', 'hr_organization_design', true, ARRAY['view', 'create', 'edit', 'delete']),
('admin', 'budget', true, ARRAY['view', 'create', 'edit', 'delete', 'export']),
('admin', 'workflow', true, ARRAY['view', 'create', 'edit', 'delete']),
('admin', 'ai', true, ARRAY['view', 'create', 'edit', 'delete']),
('admin', 'innovation', true, ARRAY['view', 'create', 'edit', 'delete']);